import Head from 'next/head';
import Layout from '../../components/layout';
import styles from '../../styles/Board.module.css';
export default function Board() {
  const checkToken = async () => {
    const token = sessionStorage.getItem('_token');
    if (!token) {
      sessionStorage.clear();
      window.location.href = '/';
    }
  };
  checkToken();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.main__title}>Hello,</h1>
        <h2 className={styles.main__text}>
          here you'll find an overview of your projects.
        </h2>
      </main>
    </div>
  );
}
Board.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
