import Head from 'next/head';
import Layout from '../../components/layout';
import styles from '../../styles/User.module.css';
export default function User() {
  const disconnect = () => {
    sessionStorage.removeItem('user');
    window.location.href = '/';
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.main__title}>My profile</h1>
        <h2 className={styles.main__text}>
          Manage your account from this page.
        </h2>
        <section className={styles.user}>
          <button onClick={disconnect} className={styles.user__button}>
            Disconnect
          </button>
          <button className={styles.user__button}>Delete account</button>
        </section>
      </main>
    </div>
  );
}
User.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
