import Head from 'next/head';
import Layout from '../../components/layout';
import styles from '../../styles/User.module.css';
export default function User() {
  const checkToken = async () => {
    const token = sessionStorage.getItem('_token');
    if (!token) {
      sessionStorage.clear();
      window.location.href = '/';
    }
  };
  checkToken();
  const disconnect = () => {
    sessionStorage.clear();
    window.location.href = '/';
  };
  const deleteUser = async () => {
    const feedback = document.getElementById('feedback');
    feedback.innerHTML = '';
    const userId = sessionStorage.getItem('_id');
    const deleteUser = await fetch(`http://127.0.0.1:4000/api/user/${userId}`, {
      method: 'DELETE',
      headers: { 'Content-Type': 'application/json' },
    });
    if (deleteUser.status != 200) {
      return (feedback.innerHTML = 'Error, please try again');
    }
    sessionStorage.clear();
    window.location.href = '/';
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.main__title}>Your profile,</h1>
        <h2 className={styles.main__text}>
          manage your account from this page.
        </h2>
        <section className={styles.user}>
          <button onClick={disconnect} className={styles.user__button}>
            Disconnect
          </button>
          <button onClick={deleteUser} className={styles.user__button}>
            Delete account
          </button>
        </section>
        <p id='feedback' className={styles.feedback}></p>
      </main>
    </div>
  );
}
User.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
