import Head from 'next/head';
import styles from '../styles/Home.module.css';
import SignInForm from '../components/signInForm';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.main__title}>Welcome to reMote</h1>
        <h2 className={styles.main__text}>
          reMote is a project management tool. Built on Next, it's a sandbox to
          try out things and ideas within a fully featured React application.
        </h2>
        <SignInForm />
      </main>
    </div>
  );
}
