import { useState } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import SignInForm from '../components/signInForm';
import SignUpForm from '../components/signUpForm';
export default function Home() {
  let renderView = [];
  const [view, setView] = useState('signIn');
  const switchToSignIn = () => {
    setView('signIn');
  };
  const switchToSignUp = () => {
    setView('signUp');
  };
  if (view === 'signIn') {
    renderView = (
      <div>
        <SignInForm />
        <p className={styles.check}>
          Don't have an account?{' '}
          <button onClick={switchToSignUp} className={styles.check__button}>
            Click here
          </button>
        </p>
      </div>
    );
  } else {
    renderView = (
      <div>
        <SignUpForm />
        <p className={styles.check}>
          Already have an account?{' '}
          <button onClick={switchToSignIn} className={styles.check__button}>
            Click here
          </button>
        </p>
      </div>
    );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.main__title}>Welcome to reMote</h1>
        <h2 className={styles.main__text}>
          reMote is a project management tool. Built on Next, it's a sandbox to
          try out things and ideas within a fully featured React application.
        </h2>
        {renderView}
      </main>
    </div>
  );
}
