import Head from 'next/head';
import Layout from '../../components/layout';
import styles from '../../styles/Create.module.css';
export default function Create() {
  const checkToken = async () => {
    const token = sessionStorage.getItem('_token');
    if (!token) {
      sessionStorage.clear();
      window.location.href = '/';
    }
  };
  checkToken();
  const createProject = (e) => {};
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.main__title}>Alright,</h1>
        <h2 className={styles.main__text}>let's configure your new project.</h2>
        <form onSubmit={createProject}>
          <button type='submit' className={styles.form__button}>
            Create
          </button>
        </form>
      </main>
    </div>
  );
}
Create.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
